apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/alxbrla/kubi-epitech/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: pullsecret
      -   command:
           - “tail”
           - “-f”
           - “/dev/null”