apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: indexer
  name: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indexer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kubi-network: "true"
        io.kompose.service: indexer
    spec:
      containers:
        - env:
            - name: AMQP_URI
              value: amqp://rabbitmq:rabbitmq@rabbitmq:5672/
            - name: ELASTICSEARCH_URI
              value: http://elastic-search:9200
          image: ghcr.io/alxbrla/kubi-epitech/indexer:latest@sha256:cf8f123262ffa6f5764d7152e43d0dfd70a72a66a4689cd1bc296e385bc507f6
          name: kubi-indexer
          resources: {}
      restartPolicy: Always
status: {}
