apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.17-management
          ports:
            - containerPort: 5672  # Puerto para la conexión de RabbitMQ
            - containerPort: 15672 # Puerto para el panel de administración de RabbitMQ
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: rabbitmq         # Usuario de administración
            - name: RABBITMQ_DEFAULT_PASS
              value: rabbitmq      # Contraseña de administración
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq  # Directorio para almacenar los datos persistentes
      volumes:
        - name: rabbitmq-data
          emptyDir: {}  # Utiliza un volumen vacío para almacenamiento temporal
